
shinyServer(function(input, output, session){

#If user selects an audit, filter the data for selected audit, if they select (All) return unfiltered table 
  audit <- reactive({
    if(input$SMRaudit %in% hb_mean$Audit){
      hb_mean %>%
        filter(Audit==input$SMRaudit)
    }
    else {
      hb_mean
    }
  })
  
#observe the audit selected by user and update the choices according to the audit selection
  observeEvent(input$SMRaudit, {
    updateSelectInput(session, inputId = "Year", choices = c(unique(audit()$Year)))
  })


#reactive year selection, returns data filtered by the year selected 
  year <- reactive({audit()%>%
      filter(Year == input$Year)})
   
  # year <- reactive({
  #   if(input$Year %in% audit()$Year){
  #     audit() %>%
  #       filter(Year == input$Year)
  #   }
  #   else {
  #     audit()
  #   }
  # })
  

  
   
#observe the year selected and update the health board choices, the (All) option is added so that users can view all HBs by default
  observeEvent(input$Year, {
    updateSelectInput(session, inputId = "Healthboard", choices = c("(All)", unique(year()$Healthboard)))
  })
  
#reactive health board selection, if a specific HB is selected filter the data further, else return the table reaturned by the reactive year()
  healthboard <- reactive({
    if(input$Healthboard %in% year()$Healthboard){
      year()%>%
        filter(Healthboard == input$Healthboard)
    }
    else {
      year()
    }
  })
  
  
  
#update the data item choices according to the SMR selected
  observeEvent(input$SMRaudit, {
    updateSelectInput(session,"DataItemName", choices = c("(All)",unique(audit()$DataItemName)))
  })  


#final output applies a data item filter if user picks a specific data item, else it returns table generated by the reactive healthboard()  
  output$data <- renderTable({
      if(input$DataItemName %in% healthboard()$DataItemName){
        healthboard()%>%
          filter(DataItemName == input$DataItemName) %>%
          select(Audit, Year, Healthboard, Hospital, DataItemName, MeanAccuracy, Accuracy)%>%
          rename("SMR" = "Audit", "Health Board" = "Healthboard", "Data Item" = "DataItemName", "Mean Accuracy Scotland" = "MeanAccuracy",
                       "Mean Accuracy Hospital" = "Accuracy")
      }
    else {
      healthboard() %>%
        select(Audit, Year, Healthboard, Hospital, DataItemName, MeanAccuracy, Accuracy)%>%
        rename("SMR" = "Audit", "Health Board" = "Healthboard", "Data Item" = "DataItemName", "Mean Accuracy Scotland" = "MeanAccuracy",
               "Accuracy Hospital" = "Accuracy")
    }
  })
})
